### PR TITLE
Feature fsi lid driven cavity

### PR DESCRIPTION
**Pull request by rubenzorrilla**

### CODE REVIEW

**Comment by loumalouomega** [comment]
Where was the problem?

**Comment by loumalouomega** [comment]
@rubenzorrilla Can you create a video for tomorrow?, I want to keep the tradition of #SimulationFriday in twitter

**Comment by rubenzorrilla** [comment]
It was a settings + mesh problem. Thanks for the help!. Regarding the video, would you prefer a *.gif animation?

**Comment by loumalouomega** [comment]
I prefer a video to upload directly on YouTube, thanks

**Pull request merged**
