### PR TITLE
SuperLUSolver must have the ExternalSolversApplication prefix

### PR DESCRIPTION
**Pull request by ipouplana**
This change is related to Kratos PR #4004

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
Should be already fixed by  #3635

**Comment by ipouplana** [comment]
Ok thanks @rubenzorrilla . The thing is that I had a warning about the name of the SuperLUSolver and so I thought I had to change it...

**Comment by rubenzorrilla** [comment]
In principle should work with the current master version. If you still have problems we can have a look to it. If you don't mind, I'll also delete the branch.

**Comment by ipouplana** [comment]
Hi @rubenzorrilla , when running my tests I get this warning while working on the current master branch (updated just a moment ago):

```
..DEPRECATION-WARNING: The linear-solver "SuperLUSolver" is defined in the "ExternalSolversApplication"
Please specify the "solver_type" including the name of the application:
"ExternalSolversApplication.SuperLUSolver"
Please update your settings accordingly, the current settings are deprecated! 
.
----------------------------------------------------------------------
Ran 3 tests in 12.014s

OK
```

**Comment by rubenzorrilla** [comment]
:confused: I've just run a structural mechanics case with the SuperLUSolver and no warning appears...

**Comment by ipouplana** [comment]
I just looked at the tests in StructuralMechanicsApplication and they all call SuperLUSolver like:

```
        "linear_solver_settings"       : {
            "solver_type": "ExternalSolversApplication.SuperLUSolver",
        },
```

or like:

```
        "linear_solver_settings"       : {
            "solver_type"         : "ExternalSolversApplication.Super_LU"
        },

```

**Comment by rubenzorrilla** [comment]
Actually, we I removed that call yesterday, and no warning appears for me. Let's wait for his opinion then.

**Comment by loumalouomega** [comment]
The best candidate to illuminate here is @philbucher , I am a little lost, so many changes in few time. It is difficult to follow the changes.

**Pull request closed without merging**
