### PR TITLE
[StructMech] Update the Truss Snap-Through Example

### PR DESCRIPTION
**Pull request by matekelemen**
This example was wildly out of date, so I brought it up to speed with current master. I also added an extra JSON for displacement control that's mentioned in the readme, but wasn't in the repo.

### CODE REVIEW

**Comment by matekelemen** [comment]
@KlausBSautter @loumalouomega

**Review by loumalouomega — APPROVED** [review]

**Comment by matekelemen** [comment]
Can someone plz add me to this repo? I can't open PRs and cannot merge them either.

**Comment by loumalouomega** [comment]
I don't have manager rights in this project anymore. @rubenzorrilla

**Comment by sunethwarna** [comment]
@matekelemen It is done :)

**Comment by matekelemen** [comment]
thx

**Pull request merged**
